In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [2]:
df=pd.read_csv("D:\PW Data Science\Regression\Logistic Regression\Flask\dataset\data_aftercleaning.csv")
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [4]:
x

male  age  education  currentSmoker  cigsPerDay   BPMeds  \
0        1   39        4.0              0         0.0  0.00000   
1        0   46        2.0              0         0.0  0.00000   
2        1   48        1.0              1        20.0  0.00000   
3        0   61        3.0              1        30.0  0.00000   
4        0   46        3.0              1        23.0  0.00000   
...    ...  ...        ...            ...         ...      ...   
4233     1   50        1.0              1         1.0  0.00000   
4234     1   51        3.0              1        43.0  0.00000   
4235     0   48        2.0              1        20.0  0.02963   
4236     0   44        1.0              1        15.0  0.00000   
4237     0   52        2.0              0         0.0  0.00000   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate     glucose  
0          80.0   77.000000  
1          95.0   76.000000  
2          75.0   70.000000  
3          65.0  103.000000  
4          85.0   85.000000  
...         ...         ...  
4233       66.0   86.000000  
4234       65.0   68.000000  
4235       84.0   86.000000  
4236       86.0   81.966753  
4237       80.0  107.000000  

[4238 rows x 15 columns]

In [5]:
y.unique()

array([0, 1], dtype=int64)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=45)

In [7]:
logistic=LogisticRegression(max_iter=150)

In [8]:
logistic.fit(x_train,y_train)

LogisticRegression(max_iter=150)

In [9]:
y_pred=logistic.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report


In [11]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[1065    6]
 [ 190   11]]
0.8459119496855346
              precision    recall  f1-score   support

           0       0.85      0.99      0.92      1071
           1       0.65      0.05      0.10       201

    accuracy                           0.85      1272
   macro avg       0.75      0.52      0.51      1272
weighted avg       0.82      0.85      0.79      1272



### Now check if Cross Validation impact

In [12]:
from sklearn.model_selection import KFold
cv=KFold(n_splits=10)

In [13]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(logistic,x_train,y_train,cv=cv,scoring="accuracy")

In [14]:
score.mean()

0.8546887796887797

### Now check if GridSearchCV impacts  

In [15]:
from sklearn.model_selection import GridSearchCV


In [16]:
import numpy as np

In [17]:
parameter={'penalty':('l1', 'l2', 'elasticnet'),"solver":('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'),'C':np.linspace(0.01,100,20)}

In [18]:
grid_class=GridSearchCV(logistic,param_grid=parameter,cv=5)

In [19]:
grid_class.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=150),
             param_grid={'C': array([1.00000000e-02, 5.27263158e+00, 1.05352632e+01, 1.57978947e+01,
       2.10605263e+01, 2.63231579e+01, 3.15857895e+01, 3.68484211e+01,
       4.21110526e+01, 4.73736842e+01, 5.26363158e+01, 5.78989474e+01,
       6.31615789e+01, 6.84242105e+01, 7.36868421e+01, 7.89494737e+01,
       8.42121053e+01, 8.94747368e+01, 9.47373684e+01, 1.00000000e+02]),
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')})

In [21]:
grid_class.best_estimator_

LogisticRegression(C=26.32315789473684, max_iter=150, solver='liblinear')

In [22]:
grid_class.best_params_

{'C': 26.32315789473684, 'penalty': 'l2', 'solver': 'liblinear'}

In [23]:
grid_class.best_score_

0.8550235349560813

In [24]:
classifier=LogisticRegression(penalty="l2",solver="liblinear",max_iter=150,C=26.32315789473684)

In [25]:
classifier

LogisticRegression(C=26.32315789473684, max_iter=150, solver='liblinear')

In [26]:
classifier.fit(x_train,y_train)

LogisticRegression(C=26.32315789473684, max_iter=150, solver='liblinear')

In [27]:
y_pred1=classifier.predict(x_test)

In [28]:
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))


[[1067    4]
 [ 187   14]]
0.8498427672955975
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1071
           1       0.78      0.07      0.13       201

    accuracy                           0.85      1272
   macro avg       0.81      0.53      0.52      1272
weighted avg       0.84      0.85      0.79      1272



In [29]:
import pickle
file=open("D:\PW Data Science\Regression\Logistic Regression\Flask\model\modelprediction.pkl","wb")
pickle.dump(grid_class,file)
file.close()